from typing import Annotated, TypedDict, Optional
from langchain.messages import AnyMessage
from langgraph.graph import add_messages


class State(TypedDict, total=False):
    #Store all the messages in the conversation, including the initial system prompt and all user and assistant messages.
    messages: Annotated[list[AnyMessage], add_messages]

    #Store the final SQL query generated by the agent.
    final_sql: Optional[str]

    #Store the final answer generated by the agent.
    final_answer: Optional[str]